//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminEntities : DbContext
    {
        public AdminEntities()
            : base("name=AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<game_type> game_type { get; set; }
        public virtual DbSet<league> leagues { get; set; }
        public virtual DbSet<league_team> league_team { get; set; }
        public virtual DbSet<match_type> match_type { get; set; }
        public virtual DbSet<pick> picks { get; set; }
        public virtual DbSet<round> rounds { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<match> matches { get; set; }
    }
}
