//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pick
    {
        public int id { get; set; }
        public int match_id { get; set; }
        public int league_team_id { get; set; }
        public int picked_team_id { get; set; }
        public Nullable<int> confidence_value { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    
        public virtual league_team league_team { get; set; }
        public virtual team team { get; set; }
        public virtual match match { get; set; }
    }
}
