//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int id { get; set; }
        public string message { get; set; }
        public string inner_exception { get; set; }
        public string controller { get; set; }
        public string method { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string source { get; set; }
    
        public virtual user user { get; set; }
    }
}
