//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public match()
        {
            this.picks = new HashSet<pick>();
        }
    
        public int id { get; set; }
        public Nullable<int> match_type_id { get; set; }
        public int round_id { get; set; }
        public int team1_id { get; set; }
        public int team2_id { get; set; }
        public Nullable<int> winning_team_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> team1_start_date { get; set; }
        public Nullable<System.DateTime> team2_start_date { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string match_outcome { get; set; }
    
        public virtual round round { get; set; }
        public virtual match_type match_type { get; set; }
        public virtual team team { get; set; }
        public virtual team team1 { get; set; }
        public virtual team team2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pick> picks { get; set; }
    }
}
