//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects_with_open_rounds
    {
        public Nullable<int> user_id { get; set; }
        public Nullable<int> league_id { get; set; }
        public string league_name { get; set; }
        public Nullable<int> league_team_id { get; set; }
        public string league_team_name { get; set; }
        public int round_id { get; set; }
        public string round_name { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> lock_date { get; set; }
    }
}
