//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payout
    {
        public int id { get; set; }
        public double payout_amount { get; set; }
        public System.DateTime payout_date { get; set; }
        public int user_id { get; set; }
        public Nullable<bool> venmo { get; set; }
        public Nullable<bool> paypal { get; set; }
        public Nullable<bool> other { get; set; }
        public string note { get; set; }
    
        public virtual user user { get; set; }
    }
}
