//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineUpLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class round_winnings_calculations
    {
        public Nullable<int> league_id { get; set; }
        public int round_id { get; set; }
        public Nullable<int> winning_score { get; set; }
        public Nullable<decimal> round_pot_value { get; set; }
    }
}
